# Generated by Django 6.0 on 2025-12-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_servers'),
    ]

    operations = [
        migrations.AddField(
            model_name='servers',
            name='description',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
