# Generated by Django 6.0 on 2025-12-22 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.servers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.users')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'server'), name='unique_user_server')],
            },
        ),
    ]
