# Generated by Django 6.0 on 2025-12-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_servers_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servers',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
