# Generated by Django 6.0 on 2025-12-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='price',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
