# Generated by Django 6.0 on 2025-12-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_donation_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='mini_description',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
